### ISSUE TITLE
Add reflectometry data using refnx

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#1014]
[This project](https://github.com/James-Durant/experimental-design/) uses refnx to simulate realistic reflectometry data.

We should add a parser for refnx data to add reflectometry to the set of data sources we include.

The following gives an idea of how to use the experimental design repo. I expect we would need to add a parser that can either use the experimental-design repo directly or use it as a guide for how to interface with refnx and what kind of problems are typical of the field (material layers and properties, beam parameters, etc).

[Benchmarking Reflectometry Fitting.docx](https://github.com/fitbenchmarking/fitbenchmarking/files/7822445/Benchmarking.Reflectometry.Fitting.docx)

Refnx also seems to offer optimisation although it may be a thin wrapper around scipy optimise https://refnx.readthedocs.io/en/latest/getting_started.html

One potential barier with using the experimental-design repo is the question of how to use it. The software is behind a GPL v3 licence so to my understanding we can't do anything like bundling it, further to this, I can't see a release on pypi so we would have to direct users to github to use it.

**Comment by jfkcooper** [comment]
If needed the license can be changed (neither I nor James know much about them other than the code should have had one, hence GPL)

**Comment by AndrewLister-STFC** [comment]
This is now in Pypi called HOGBEN https://pypi.org/project/HOGBEN/
