### ISSUE TITLE
Confusing error when installing fitbenchmarking when the python version is too low

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#1029]
If pip installing with too low a python version, you get a failure of the form:
![image](https://user-images.githubusercontent.com/13645545/154656119-3c0ac064-5595-45d9-b9c0-0ce2f9e60420.png)

The minimal python version we support should be a requirement of a package so that the user gets a helpful error message.

**Comment by AndrewLister-STFC** [comment]
From Pandas website:
> Python version support
> Officially Python 3.7.1 and above, 3.8, and 3.9.
