### ISSUE TITLE
Add support for Theseus NLS solver

### ISSUE THREAD

**Issue by talassio** [fitbenchmarking/fitbenchmarking#1052]
**Add the Theseus NLS solver to the benchmarks**

Theseus is an efficient application-agnostic library for building custom nonlinear optimization layers in PyTorch to support constructing various problems in robotics and vision as end-to-end differentiable architectures but it is also a stand-alone NLS.

https://sites.google.com/view/theseus-ai/

Reference: https://arxiv.org/pdf/2207.09442.pdf

**Comment by AndrewLister-STFC** [comment]
Thanks for the suggestion, looking at the link it would be good to get this in at the same time as Ceres
