### ISSUE TITLE
All data files convert to ASCII format

### ISSUE THREAD

**Issue by bb511** [fitbenchmarking/fitbenchmarking#107]
The neutron data files are currently in NeXuS format. This format requires Mantid to be read which makes the FitBenchmarking tool dependent on a certain fitting software. We want to eliminate this dependency and hence replace all the NeXuS files with ASCII files.

Additionally, the tool should require a specific problem definition format.  This format would be refined over time. The current status where NIST problems are defined one way and Neutron problems another way makes the code very long since one has to deal with specific cases when reding in the data and problem definition details. Hence, FitBenchmarking is less extendable by other users as right now, the process of reading problem files and getting them in the correct format for the fitting software is pretty convoluted.

Finally, the WISH17707 problems require `ignore_invalid = False` through an adhoc exception. This is because the data file contains errors which are 0 which makes no sense when considering physical data. FitBenchmarking should display a warning when the user provides that with errors that are not sensible. However, it should carry on with the benchmarking, but without weighting by the errors.

**Comment by bb511** [comment]
@Anders-Markvardsen Should this be higher on the priority list?

**Comment by Anders-Markvardsen** [comment]
From user feedback this one was not mentioned hence the reason for low. however, removed low priority there made it a medium-ish priority issue

**Comment by Anders-Markvardsen** [comment]
@AtomAnu see here issues we discussed earlier. As discussed when creating ascii files from (save them as .txt) then in mantid first convert all zero error values to ones, i.e. in accordance with the default Mantid behavior
