### ISSUE TITLE
Docker build fails locally

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#1081]
I get the following error when trying to build fitbenchmarking in the docker container locally:
![image](https://user-images.githubusercontent.com/13645545/200789747-a0a0c594-a676-4fc8-b1a1-aefcc5a8469d.png)

This worked for me locally on Friday, so I'm not sure what's changed.

**Comment by AndrewLister-STFC** [comment]
Google suggests: `pip install --upgrade --upgrade-strategy eager -e .` as a way to get pip to upgrade if possible (https://stackoverflow.com/questions/55804822/pip-install-latest-dependency-versions). Although I guess I'm going to need to upgrade the docker container again for a real fix.
Are you expecting a new RALFit? If so I'll update it to add the latest when that's available.

**Comment by tyronerees** [comment]
> Are you expecting a new RALFit? If so I'll update it to add the latest when that's available.
Yes -- I've pushed changes to master in RALFit.  I need to test it with FitBenchmarking to check it does what I need it to do, but all works when calling it from a standalone python script now.

**Comment by tyronerees** [comment]
@tyronerees  to test again and update and/or close

**Comment by jess-farmer** [comment]
Closing - can be reopened if needed
