### ISSUE TITLE
Descriptions in minimizer tests

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#1102]
The Minimizer option tests:

https://github.com/fitbenchmarking/fitbenchmarking/blob/a499b7efb3c4fbbde8d1f88238e86a1a6b7af933/fitbenchmarking/utils/tests/test_options_minimizers.py#L13-L16

say they check that all *valid* minimizers are set correctly.  They actually seem to check that all *default* minimizers are set correctly.  We also do the same for the docstrings in the individual minimizers:

https://github.com/fitbenchmarking/fitbenchmarking/blob/a499b7efb3c4fbbde8d1f88238e86a1a6b7af933/fitbenchmarking/utils/tests/test_options_minimizers.py#L74-L77

**Comment by AndrewLister-STFC** [comment]
Closed by #1138
