### ISSUE TITLE
Title of webpage should be changed

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#1123]
The results pages html files currently have a generic name.  This should reflect what is being run in the test.

**Comment by joshuadkitenge** [comment]
@AndrewLister-STFC @tyronerees The current method, with the generic name, currently appears to be the best option. There are too many combinations for how to run fitbenchmarking. While it may work well with one optimization software, if multiple are used, the resulting name would become too long. One potential solution could be to allow the user to set the name in the benchmark problem file. Do you have any thoughts on this?

**Comment by AndrewLister-STFC** [comment]
Perhaps a prefix in the options file would be best
