### ISSUE TITLE
Horace parser/controller cleanup changed

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#1132]
Jacob has passed on that we need to update calls to `horace_off; herbert_off` with:
```
try
    herbert_off();
catch ME
    switch ME.identifier
      case "MATLAB:UndefinedFunction"
          % Ignore warning
      otherwise
          rethrow(ME);
    end
end
```

This will need to be done for a FitBenchmarking IDAaaS workspace to be useful to the PACE team.

**Comment by AndrewLister-STFC** [comment]
It might be just as good to remove the call to `herbert_off` without this additional code if the stable horace version (not their git master branch) is not currently supported.

**Comment by joshuadkitenge** [comment]
#1133 this problem has been fixed in this pr
