### ISSUE TITLE
Allow multiple ways to report timings

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#1148]
The average time over a set of runs might not be the best figure to report -- for example, if there's a delay in one of the runs, taking the average would reflect that.

We should offer a range of stats (mean, std dev, min, max, first,...) 

The docs for `timeit` suggest that we shouldn't be using std dev, as it doesn't mean anything.

**Comment by tyronerees** [comment]
Here's a couple of links arguing to use the minimum time for benchmarking:

https://betterprogramming.pub/the-mean-misleads-why-the-minimum-is-the-true-measure-of-a-functions-run-time-47fa079075b0

https://lemire.me/blog/2023/04/06/are-your-memory-bound-benchmarking-timings-normally-distributed/

**Comment by AndrewLister-STFC** [comment]
In docs we should explain example workflow for refinement, and explain that the stats are a guide, so not certain.

**Comment by AndrewLister-STFC** [comment]
Julia seems to do this nicely: 
![image](https://github.com/fitbenchmarking/fitbenchmarking/assets/48282025/36b7d6e5-acf0-4f79-9430-642c1d8287bb)
