### ISSUE TITLE
Change rendering of html plotly plots

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#1183]
Plotly plots introduced in #1164 all embed the full plotly.js in the html file, meaning each file is ~3MB big.

This can be avoided by shipping our own library.

We can also just generate the div needed, rather than the full html page, which would remove the need for an iframe.

This is a useful [StackOverflow post](https://stackoverflow.com/questions/36262748/save-plotly-plot-to-local-file-and-insert-into-html)

**Comment by AndrewLister-STFC** [comment]
This looks like it can be done by switching to [write_html](https://plotly.com/python/interactive-html-export/#full-parameter-documentation)
```
fig.write_html(file, include_plotlyjs=<path to single plotlyjs lib>)
```
