### ISSUE TITLE
Add matlab fitting

### ISSUE THREAD

**Issue by bb511** [fitbenchmarking/fitbenchmarking#119]
Add Matlab fitting software to FitBenchmarking.

Matlab can be called from Python using the Matlab Engine API for Python.  I find the [official Matlab docs](https://uk.mathworks.com/help/matlab/matlab-engine-for-python.html#:~:text=The%20MATLAB%20Engine%20API%20for%20Python%20provides%20a,of%20Python%20Compatible%20with%20MATLAB%20Products%20by%20Release.) a bit terse, but this seems to be a good tutorial: https://mscipio.github.io/post/matlab-from-python/

Here is a guide to some methods for curve fitting in Matlab:
https://walkingrandomly.com/?p=5196#:~:text=Pure%20MATLAB%20solution%20%28No%20toolboxes%29%20In%20order%20to,not%20be%20suitable%20for%20more%20complex%20fitting%20problems.

I think we should implement, from this article:
- Pure MATLAB solution
- MATLAB with optimization toolbox
- MATLAB with statistics toolbox
- MATLAB with curve fitting toolbox

Each of these should probably be a separate controller (and we should make sure we explore any options within these toolboxes).  Note that these toolboxes need to be installed when matlab is installed -- there'll be an option to pick which toolbox to use (we have a licence for all at STFC).

**Comment by tyronerees** [comment]
Here is a MWE to solve the DANWOOD NIST example using scipy and matlab's no-toolbox minimizer:
[python-matlab.zip](https://github.com/fitbenchmarking/fitbenchmarking/files/6445940/python-matlab.zip)
(to run, call `python danwood.py` on a system with matlab installed, and from a compatible version of python)

I couldn't find a way to do it without writing Matlab code too, but the m-file needed is fairly straightforward.  Also, there may be neater ways to do it, I'm not sure all the type casting is necessary, etc, but thought I'd share in case this helps.

**Comment by jess-farmer** [comment]
Closing, as all toolboxes have now been added
