### ISSUE TITLE
Add parser/file format for inputting a sparse jacobian

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#1208]
If problems already exist with sparse jacobians, we should use those. Otherwise we need a format to define the sparsity and values of the jacobian (possibly just a python file).

We also need to define the sparse matrix format and be flexible on it. scipy_ls want's csr for performance reasons but other packages may need csc or coo to provide the optimal performance.

Is the format going to be an option for comparisons, a quirk of a problem, a quirk of the solver, or fixed?

- [x] How do we define a sparse jacobian?
- [x] Which sparse matrix format do we store it in?
- [x] Write a parser to handle the conversion.

Update 15.2.24

@tyronerees @jess-farmer @AndrewLister-STFC and @Letizia97 discussed this in a meeting.  We will:
 - use whatever jacobian format is native to the parser (e.g., coo for SIF files)
 - convert where need in the controller, or allow the software to convert if possible
 - document parser types and any preferred formats for fitting software so 'best' pairs are highlighted.
We also need to save 'fitting_problem.sparse_jacobian' alongside the dense 'fitting_problem.jacobian'.

**Comment by tyronerees** [comment]
For SIF problems, the sparse analytic jacobian (in coo format) can be obtained using `slagjac`: https://jfowkes.github.io/pycutest/_build/html/methods/pycutest.CUTEstProblem.slagjac.html
