### ISSUE TITLE
Add flags to controllers where sparsity is handled

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#1209]
We need to tag all controllers that can handle sparsity and where required, edit the controllers to allow for it.

Controllers that are able to offer sparsity:
- [ ] gsl
- [ ] scipy_ls
- [ ] matlab_opt

Controllers that may offer sparsity (more investigation needed):
- [ ] levmar (sparseLM)
- [ ] theseus

**Comment by AnthonyLim23** [comment]
Is there an easy way to tell if a problem is likely to result in sparsity?
