### ISSUE TITLE
Cannot set up ties on mantid functions

### ISSUE THREAD

**Issue by bb511** [fitbenchmarking/fitbenchmarking#121]
Currently, when running the fit benchmarking software with scipy, ties cannot be set up through the mantid python api. This should be investigated and fixed, as it generates an ad-hoc exception in the code (i.e. scipy ignores the GEM problem as it is the only one that contains ties) .

The exception is currently in fitbenchmark_one_problem.py and look for:

```
        if 'GEM' in problem.name and user_input.software == 'scipy':
            break
```

This problem should be easier to fix by consulting [here](https://docs.mantidproject.org/nightly/concepts/FitFunctionsInPython.html)

**Comment by Anders-Markvardsen** [comment]
String
```
if 'GEM' in problem.name and user_input.software == 'scipy'
```
no longer present in fitbenchmark_one_problem.py
