### ISSUE TITLE
Acc and runtime performance profiles show different n failures for same solver

### ISSUE THREAD

**Issue by Letizia97** [fitbenchmarking/fitbenchmarking#1240]
When running the NIST/average_difficulty problems, one can see that in the performance profile plots, certain solvers are marked as having a certain number of failures based on the accuracy plot, but no failure based on the runtime plot. See 'dream [bumps]' and 'newton [bumps]' in the picture below, they are marked as having failed in the legend of the accuracy plot but not in the runtime plot.

The number of failures (to display in the plots' legends) is determined in function create_plot in performance_profiler. The upper bound to determine failures is set to 1.0e20, which might be causing the problem in these examples.

![pp](https://github.com/fitbenchmarking/fitbenchmarking/assets/28632706/dc01367f-f3ec-4789-a6fb-8f1f07517851)

**Comment by tyronerees** [comment]
@AndrewLister-STFC to check that it's fixed
