### ISSUE TITLE
When using load_checkpoint on old results (previous to last run), Dash pp plots are not shown

### ISSUE THREAD

**Issue by Letizia97** [fitbenchmarking/fitbenchmarking#1253]
When one uses load_checkpoint to visualise results that are older than the one from the last run, the Dash app fails to display the performance profiles. When one clicks the online button, a blank space is shown in place of the pp plot, and no warning is given. 

From the terminal it's possible to see that a Dash app is running, but we get an error in display_page (see traceback attached).
<img width="622" alt="traceback" src="https://github.com/fitbenchmarking/fitbenchmarking/assets/28632706/d4ca4952-a7f2-4a28-befa-21e8ee84c4a2">

Checking the url for the broken pp plot, I saw that the Dash app available at that url was broken (it just appeared as a blank page), while the only Dash app still running was the one associated with the latest run, so at a different URL.

**Comment by AndrewLister-STFC** [comment]
To recreate:
1. Run `fitbenchmarking -p examples/benchmark_problems/NIST/low_difficulty` and don't close the web page but kill dash (ctrl+c).
2. Run `fitbenchmarking -p examples/benchmark_problems/NIST/average_difficulty` and don't kill dash.
3. Go back to the first webpage and try to open any online plot.
