### ISSUE TITLE
Wrong error when the problem name contains special characters 

### ISSUE THREAD

**Issue by AnthonyLim23** [fitbenchmarking/fitbenchmarking#1276]
When testing another bug fix, I found a new bug. 

If I put the following in a problem definition file 

```
name = '$Q = 0.4628 \\AA$'
```

I will always get the error
```
The filepath for saving a file is too long.
Details:
   Please change the results directory so that it is well within the 260 character limit.
```

even if the file path is shorter than other things that do run. Changing the name to
```
name = 'Q = 0.4628 AA'
```
fixes the problem. 

I think we should at least have an error message that reflects the actual error.

**Comment by RabiyaF** [comment]
I wasn't able to recreate this issue on my end. When I tried it seemed to work fine. 

<img width="893" alt="image" src="https://github.com/user-attachments/assets/f737a45b-8d1b-4107-9b21-0cb7ac8e7ded">

**Comment by RabiyaF** [comment]
However I found an issue with the links not working properly when special characters are included in the name. Best not to include them. Maybe some sort of verification can be added when parsing the problem defination file.
