### ISSUE TITLE
Extend to be able to benchmark against custom fit functions

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#129]
Currently only fit functions that can be created through Mantid build-in fit functions can be tested against.

Extend this to include any Python calculable fit functions.

This will require that such custom fit functions are either shipped with the repository and/or pull down from an external repository.

**Comment by Anders-Markvardsen** [comment]
This issue need discussion first in Friday catch up before work is started on it

**Comment by AndrewLister-STFC** [comment]
@Anders-Markvardsen I'm closing his issue as I think it is outdated.
This could refer to being unable to run say NIST problems (which define a custom function) with Mantid, in which case I believe it has been fixed.
Or it could refer to what is described in #266, which I believe has more information on the issue.

If I have missed the point of this issue, please reopen it.
