### ISSUE TITLE
The main workflow

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#1315]
In the main workflow on github actions (https://github.com/fitbenchmarking/fitbenchmarking/blob/master/.github/workflows/main.yml), everything is run in an environment. Consider changing this so that behaviour is the same as seen on the nightly builds.

**Comment by AndrewLister-STFC** [comment]
This looks a bit like what’s in #1312

**Comment by RabiyaF** [comment]
After the container update, I noticed that the full test are taking longer. In RasCAL-2, some test are only run after the PR is reviewed/approved. Maybe we can also do something like that for the full tests.

<img width="289" alt="image" src="https://github.com/user-attachments/assets/923b8051-b391-476b-9de0-230896cb1fdb">
