### ISSUE TITLE
Allow users to comparing minimizers from scipy, mantid, other in one table

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#132]
Allow user to run a fit benchmarking with a mixture of different sources of minimizers (e.g. mantid and scipy) and where the relative scores of these against selected benchmarking problems is shown in a table. 

At present FitBenchmarking only create tables which shows comparisons in scores between minimizers available from one software, and separate tables are produced for each software

**Comment by AnthonyLim23** [comment]
I believe this is to allow the user to run a fit benchmarking with a mixture of different sources of minimizers (e.g. mantid and scipy).
