### ISSUE TITLE
Add default FitBenchmarking options file

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#167]
Current we have minimizers_list_default.json which set the default minimizers which FitBenchmarking will be compared for each software.

As of now it reads:

```   
{
    "mantid" : ["BFGS", "Conjugate gradient (Fletcher-Reeves imp.)",
                "Conjugate gradient (Polak-Ribiere imp.)",
                "Damped GaussNewton",
                "Levenberg-Marquardt", "Levenberg-MarquardtMD",
                "Simplex","SteepestDescent",
                "Trust Region"],
    "scipy" : ["lm", "trf", "dogbox"]
}
```

Simply change the name of the file to fitbenchmarking_default_options.json and update all documentation and code that previously referred to minimizers_list_default.json

**Comment by AndrewLister-STFC** [comment]
@wathen suggested I start with #134 which mentions this in the description.

@Anders-Markvardsen, can you confirm that the documentation referenced is the GitHub wiki? I couldn't see anything on this file in there.
I can fix the results from a grep ("example_scripts/" and some values in "utils/misc.py" and "utils/tests/test_misc.py"), but if it's in other locations too, I may need a pointer.

**Comment by Anders-Markvardsen** [comment]
There may not be any documentation on this setting file in the wiki yet - hence with this change preferable but optionally document that with the change in this issue we will then above a global setting files.


However as a minimum to a grep on all sort files for minimizers_list_default.json and change accordingly. Thanks and welcome

**Comment by AndrewLister-STFC** [comment]
Since other options need to be added I should extend this so that the minimisers are a single option in the file, and are collected that way. (e.g. `json.load(open(options_file))['minimizers']`
