### ISSUE TITLE
Automated tests for our example scripts

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#169]
Currently, the system tests seem to be outdated and misconfigured. The [generator file](https://github.com/fitbenchmarking/fitbenchmarking/blob/master/systests/generate_current_results.py) is creating scipy tables while the currently available answer files are for mantid only. However, the tests seem to pass on travis. For more details see [this build](https://travis-ci.org/fitbenchmarking/fitbenchmarking/jobs/559448482).

To solve this, one should:
* First change the generator file to produce mantid tables and see if the Travis tests still pass. If they don't, investigate why and solve this issue.
* Add a set of answer files for scipy, like the [mantid ones](https://github.com/fitbenchmarking/fitbenchmarking/tree/master/systests/expected_results).
* Write code that generates both mantid and scipy tables and compares them with the answer files, replacing the [current generator file](https://github.com/fitbenchmarking/fitbenchmarking/blob/master/systests/generate_current_results.py).
* Try to make the tests fail on purpose and see what is travis's response. If even when the tests should fail, the return code is 0, investigate why.

**As an aside:** once sasview is added, it should be included in the system test as well, so by solving this issue you should have an easier time later on.

**Comment by bb511** [comment]
@Anders-Markvardsen @AtomAnu The system test already does this. However, I was checking it today and realised it is currently broken and outdated, even though it exits with 0 on travis (and thus travis thinks everything passed). I think it should be high priority to solve these system test related issues.

**Comment by Anders-Markvardsen** [comment]
@bb511 Please don't hesitate to edit this one thanks

**Comment by tyronerees** [comment]
Example scripts added since this issue was opened.  Will be addressed by new system tests.
