### ISSUE TITLE
Better documenting how function evaluations is done

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#182]
This issue may be best done after #210 has been resolved

It was highligthed in todays Friday catchup that the documentation on how fitbenchmarking does function evaluation is not documented in enough detail, for example, to:

* explain how function evaluation is done when e.g. Scipy minimizers are used against Mantid fitting function, such as Mantid in-build BackToBackExponential and so on. This will be important for the user to know so they clearly can understand what they are comparing

**Comment by tyronerees** [comment]
closed by #263
