### ISSUE TITLE
Add way to get info about each minimizer from table

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#196]
An example table output is:

![Capture](https://user-images.githubusercontent.com/1135476/63273114-41b7f000-c295-11e9-8650-5437e970b9ce.PNG)

In meeting today we agreed that the user should have the option to click on any of the minimizer names in the top row and then be presented with information about the minimzers which the user clicked on. Ideally this would just be an URL for each minimizer.

Important this option must be optional.

**Comment by AndrewLister-STFC** [comment]
Marking this as blocked and coming up with a proposal as I believe for this to be done properly some work must be done on how options are handled.
