### ISSUE TITLE
Remove/adjust/document 0.00000001 error assignment

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#202]
In prepare_data.py files we have a hidden secret:

```
problem.data_e[problem.data_e == 0] = 0.00000001
```

This line of code hopefully rarely/never get executed. Do we really need to do this hard coded assignment of a error. If the answer is yes then the reason for this need to documented to users, including why exactly '0.00000001' and further '0.00000001' need to be set globally for FitBenchmarking.

In the first instance understand if this line is ever executed and if yes when. Then discuss with Anders and/or Friday catchup.

**Comment by AndrewLister-STFC** [comment]
Update:
This is now in `fitting.controllers.base_controller.Controller_correct_data()`
and has been edited so looks like:
```
            self.data_e[self.data_e == 0] = \
                np.min(self.data_e[self.data_e != 0]) * 1e-8
```

Although it is still undocumented and whether it's necessary is unknown (to me).

**Comment by Anders-Markvardsen** [comment]
copy what has been in bumps
