### ISSUE TITLE
Replace copied sascalc with download of these files

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#203]
In #199 support for SasView was added with temporary added a copy of sascalc files as explained in that PR.

In this issue delete files in top level sas folder and replace this with install that:

* clone a specific version of the SasView repo in read only mode. The specific version is to guard against the expected future changes of this part of the sasview codebase
* copy the sascalc part of the SasView repo to a location where it is visible to python as appropriate
* delete the cloned sasview repo

See https://stackoverflow.com/questions/2472552/python-way-to-clone-a-git-repository for suggestions for how a github repo can be cloned

**Comment by AndrewLister-STFC** [comment]
Sascalc is no longer required as the data is now parsed with a bespoke function (as of #377)
