### ISSUE TITLE
Documentation of code out of sync in top level files 

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#205]
Code documentation of functions, function parameters and code comment has gone out of sync for fitting_benchmarking.py and fitbenchmark_one_problem.py and some of the functions it calls.

Fix:
* documentation for all function parameters
* check these are not out of date (and therefore currently wrong)
* add code explaining the code in do_benchmarking (in this function should problem_groups be problem_group and block be file?)

These two level python are particular important to be well documented since they form entry points to the other parts of FitBenchmarking.

Observed while testing #199

**Comment by AndrewLister-STFC** [comment]
I can't see the benefit in passing a dict and a name if the only time it's used is to get that item from the dict. 
Is there any reason I cant change do_benchmarking to be:
`def do_benchmarking(user_input, problem_group)`
