### ISSUE TITLE
Merge existing FitBenchmarking and SASView problem formats

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#209]
With #199 a new format problem definition file format is added as described in benchmark_problems/README.md

A longer term concern I have, is if a new problem definition file format needs to be added for every new software FitBenchmarking support since sounds like recipe for a longer term maintenance problem. 

It this issue, as a follow up to #199, investigate options for merging the FitBenchmark and sasview problem definition formats into a new format that can be used to describe both while being accommodable to support of other software in the future

====== **EDIT** (26/11/19) ==================
After the refactor of how parsing is done (#264), both of these parsers show very similar code.

This will require a new variable in the format to select which software to use for the function evaluation.

**Comment by AndrewLister-STFC** [comment]
@Anders-Markvardsen This issue already exists.

**Comment by AndrewLister-STFC** [comment]
During the recent workshop we reviewed this issue and decided on a format with "fit_ranges" and "parameter_ranges" expressed in the format `fit_ranges = {'x': [1, 5], ...}` meaning 1<x<5.

We also discussed the format of the function string but this was suggested as a future issue.
