### ISSUE TITLE
Have code for creating functions for different software in one place

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#210]
Within the parsing folder, get_function() of a FittingProblem(base_fitting_problem.BaseFittingProblem) returnes callable function and starting parameters. As of now (it seems) return this in SciPy format for all cases.

Code is also present to create callable function in files within the fitting folder. For example in fitting/mantid/func_def.py:

```
def function_definitions(problem):
    """
    Transforms the prob.equation field into a function that can be
    understood by the mantid fitting software.

    @param problem :: object holding the problem information

    @returns :: a function definitions string with functions that
                mantid understands
    """

    problem_type = extract_problem_type(problem)

    if isinstance((problem.get_function())[0][0], FunctionWrapper):
        function_defs = [problem.get_function()[0][0]]
    elif problem_type == 'NIST':
        nb_start_vals = len(problem.starting_values[0][1])
        function_defs = parse_function_definitions(problem, nb_start_vals)
    elif problem_type == 'SasView'.upper():
        function_defs = parse_sasview_function_definitions(problem)
    else:
        raise NameError('Currently data types supported are FitBenchmark'
                        ' and nist, data type supplied was {}'.format(problem_type))

    return function_defs
```

Hence at present we seems to create functions needed for different software in two places, i.e. within the parsing folder and within the fitting folder. 

Can we do better and keep code for creating functions in one place? The above is already hard to read and this will only get worse with more software added.

Observed while testing #199.

**Comment by tyronerees** [comment]
Fixed by PR #263
