### ISSUE TITLE
Move from Python 2 to Python 3

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#213]
Python 2 is being sunsetted on January 1st 2020:
https://www.python.org/doc/sunset-python-2/
and advice from Python is that "You should upgrade to Python 3 as soon as you can".

The last version of NumPy to support Python 2.7 was numpy 1.16.x (it's now 1.17.2). The last SciPy version to do so was 1.2.x (it's now at 1.3.1). FitBenchmarking should be upgraded to ensure it continues to use the latest software, and that it remains easy to install.

**Comment by arm61** [comment]
python 2.7 is currently required for mantid...

**Comment by tyronerees** [comment]
Indeed, and I believe SasView also currently needs Python 2, so we can't do away with Python 2 altogether now.  We should try to write code which is Python 2 and 3 compatible, using `import future` and the like, to make it as easy as possible to switch to Python 3 when the other packages do make the leap.

**Comment by AndrewLister-STFC** [comment]
[Mantid](https://github.com/mantidproject/mantid/releases/tag/v4.2.0)
[SASView](https://github.com/SasView/sasview/releases/tag/v5.0.0)
Latest versions are both python 3 compatible (according to these pages, and unless mantid is planning to switch over on a single release).

We should pick this up again.

**Comment by wathen** [comment]
Mantid python3 installation is currently not available -- expected installation mid January. This issue is blocked until then.
