### ISSUE TITLE
Implement GSL natively

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#218]
Mantid's minimizers are actually just hooks to the relevant functions in the GNU Scientific Library.  Implement a call to the GSL directly from Mantid
GSL Nonlinear least-squares fitting:
https://www.gnu.org/software/gsl/doc/html/nls.html
Python interface:
http://pygsl.sourceforge.net/README.html

**Comment by tyronerees** [comment]
Issue #247 needs to be fixed before this is addressed

**Comment by wathen** [comment]
Having looked into GSL, Levenberg-Marquardt is called using `pygsl/multifit_nlin` and the rest of the minimizers are called in `pygsl/multiminimize.py`.  The setup is pretty different for both so might be worth adding them as as `gsl_lm` and `gsl_min`, or something similar?
