### ISSUE TITLE
Move documentation to Sphinx

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#219]
Move the docs from the GitHub wiki to Sphinx. 
- [x] Set up sphinx, with placeholders for user and developer documentation
- [x] Set up to compile and display on readthedocs.com
- [ ] Move across the existing documentation to the new format

**Comment by AndrewLister-STFC** [comment]
To set up a readthedocs account for the project. The easiest method would be to reuse the FitBenchmarking account from GitHub.
@Anders-Markvardsen can you create the account [here](https://readthedocs.org/accounts/signup/)? There is a useful video [here](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html) which mentions the readthedocs steps from around 14:20 to the end.
Alternately, I can do it if you give me the details.

**Comment by Anders-Markvardsen** [comment]
Hi Andrew I have made your owner hence you then have the same permissions as I have. Can you now setup readthedocs?

**Comment by AndrewLister-STFC** [comment]
Yes, I should be able to

**Comment by AndrewLister-STFC** [comment]
Should be set up to automatically update here:
https://fitbenchmarking.readthedocs.io/en/latest/

**Comment by tyronerees** [comment]
Reopening as the existing wiki hasn't been moved to the read-the-docs format
