### ISSUE TITLE
Review column formatting

### ISSUE THREAD

**Issue by wathen** [fitbenchmarking/fitbenchmarking#222]
As observed in #220, the width of the first column containing the names of the data sets is much longer than necessary.

**Comment by AndrewLister-STFC** [comment]
More information on this issue:

When looking at a html output from Fitbenchmarking, some of the table withs are much larger than necessary as below.

![image](https://user-images.githubusercontent.com/48282025/67682581-9cea1b00-f987-11e9-94e1-b1642299a977.png)

**Comment by AndrewLister-STFC** [comment]
Tables can be set to auto width but seem to need a title (which we might want anyway?):
![image](https://user-images.githubusercontent.com/48282025/67700961-ebf37880-f9a6-11e9-8f94-38d2717c41fb.png)

**Comment by wathen** [comment]
@Anders-Markvardsen What do you think about the auto formatting of the columns?
