### ISSUE TITLE
Too many plots open error

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#227]
Plots should be closed after they are saved.

Also need to solve reason for tihs symptom
```# Avoid reaching the maximum recursion depth by setting recursion limit
# This is useful when running multiple data set benchmarking
# Otherwise recursion limit is reached and the interpreter throws an error
sys.setrecursionlimit(10000)
```

Form GitHub history this was to do with a tkinter issue so matplotlib could be the cause of this.

**Comment by arm61** [comment]
commenting the `setrecursionlimit` line out on macOS 10.14.5 (python 2.7) doesn't change anything
