### ISSUE TITLE
Code does not comply with PEP8

### ISSUE THREAD

**Issue by arm61** [fitbenchmarking/fitbenchmarking#238]
**Description of the error**
Currently the code does not comply with PEP8

**Describe the expected result**
The code should be beautiful and PEP8 formatted

**Describe the actual result**
It is not.

**Suggested fix**
Make sure that no issues arise when **both** flake8 and and pylint are run

**Additional details**
N/A

**Comment by TOFarmer** [comment]
When this is fixed, do we want to add a pylintrc file, so that we can specify our listing conventions?  For instance I think the pylint default line length is 100, not 79.

**Comment by tyronerees** [comment]
Closing this, and we'll add specific issues for code that's not PEP8 compliant as we come across them.
