### ISSUE TITLE
Mantid example scripts warnings

### ISSUE THREAD

**Issue by TOFarmer** [fitbenchmarking/fitbenchmarking#241]
**Description of the error**
Running the Mantid example script (example_runScripts_mantid) results in a large number of warnings. Most of these seem innocuous, but the following two could indicate the fitting process is flawed:

```
Fit-[Notice] Fit started
Fit-[Warning] Fit status: Failed to converge after 0 iterations.
Fit-[Warning] Stopped after 0 iterations
Fit-[Notice] Fit successful, Duration 0.00 seconds
```
```
Instrument-[Warning] In Instrument::getSamplePos(). No SamplePos has been set.
IFunction1D-[Warning] No sample set for instrument in workspace.
IFunction1D-[Warning] Can't calculate wavelength in IkedaCarpenter.
IFunction1D-[Warning] Default all wavelengths to one.
IFunction1D-[Warning] Solution is to load appropriate instrument into workspace.
```

**Describe the expected result**
No warning about only trying for 0 iterations.
No warning about lack of wavelength for IkedaCarpenter. 

**Describe the actual result**
Shown above.

**Suggested fix**
This depends on whether this is expected behaviour or not.  If it is expected that a large number of fits should not actually try to iterate and fail, then I would ensure that the warning is hidden.  If it is unexpected then why these fits are failing needs to be addressed.  The IkedaCarpenter warnings can probably just be suppressed.

**Comment by Anders-Markvardsen** [comment]
will be fixed in #168
