### ISSUE TITLE
Unify the fitting functions in the code

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#247]
At the moment, if you want to add a new fitting routine, you have to copy the existing code in `fitbenchmarking/fitting/<existing_fitting_method>/` to `fitbenchmarking/fitting/<new_fitting_method>/`, and modify.  Much of the code will remain exactly the same, with only minor changes needed between different packages.  

We should restructure this part of the code so that a global method does things that are common to all fitting methods.  Boilerplate code that needs to be copied across all minimizers should be kept to a minimum, as this makes maintenance and adding new features difficult as more minimizers are supported by FitBenchmarking.

Supporting documentation should make it clear to a user adding custom minimizers where fitbenchmarking keeps its data, function evaluations, etc., and what API they should hook their minimizer into so that it can be incorporated into fitbenchmarking.  

(Possibly sufficiently related to issue #210 both could addressed at once?)

**Comment by AndrewLister-STFC** [comment]
Talked through with @wathen and @tyronerees, and we decided that the following might be clearer and thereby easier to maintain with adding new minimizers:

- Parse all problems into a single fitbenchmarking internal format
- Convert problems to the required software format just before running
- Convert all answers back after running

This will mean that any new additional minimizers will only need to implement 3 functions (which can be enforced by an abstract base class):
- prepare_problem
- fit
- unpack_solution

And adding new problem types is a single function:
- parse_problem

Further to this, the prepare_problem function will be fully deterministic so can utilise a cache if converting just before running is too expensive.
