### ISSUE TITLE
Refactor the software options dictionary to make it more user friendly

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#260]
The current method of defining options is both complicated for the user and hard to maintain.

Options should be controlled in a single place so that setting an option is consistent, with priority:
1. Values set in the example script.
2. Values set in the options file.
3. Values set as a default programmatically.

Options should also be able to be set easily, and have clearly defined default values.

**Comment by tyronerees** [comment]
related to #231?

**Comment by AndrewLister-STFC** [comment]
This issue needs rewording as per our discussion last week

**Comment by AndrewLister-STFC** [comment]
I think switching from json to [configparser (.ini)](https://docs.python.org/2.7/library/configparser.html) compatible files would be good.

It has less clutter like the brackets in json, and looks a bit more presentable.

In my first draft of this, I'll use config parser, but I can change it if people prefer json
