### ISSUE TITLE
Mantid example script performance with pytest

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#267]
**Description of the error**
When the example_scripts tests are run with pytest, example_scripts_mantid.py is taking a long time to run (20mins+). This is in contrast to running the script outside of pytest which takes ~5mins.

**Describe the expected result**
Running the tests with pytest should not add such a large overhead. If there is an overhead I would expect it to be much less than the runtime for the fitting.

**Describe the actual result**
Pytest is causing a very large slowdown.

**Additional details**
From quick tests it looks like it is only the mantid script which is having issues.

Perhaps pytest is throttling memory and leading to swapping or something similar?

**Comment by AndrewLister-STFC** [comment]
> A solution to this would be to make the mantid verison of simple_tests (which will be created in #265) the default run by the mantid example script -- these should be small enough to not give Travis any issues, but would test Mantid is working correctly.

I've noticed it on my machine too, running the example is fine, but putting it through pytest fails.

**Comment by Anders-Markvardsen** [comment]
Done in different issue
