### ISSUE TITLE
Fitbenchmarking should use higher difficulty problems.

### ISSUE THREAD

**Issue by andyfaff** [fitbenchmarking/fitbenchmarking#270]
There are many problems created for testing global minimisers. These problems generally have many local minima and only one global minima. The efficacy and efficiency of a minimiser to find the global minima is vital in many scattering analyses where the energy landscape is very complex. In such systems the utility of Levenberg-Marquardt (etc) is next to useless.
I suggest Fitbenchmarking should introduce many more global test functions (e.g. https://github.com/scipy/scipy/tree/master/benchmarks/benchmarks/go_benchmark_functions) for characterising minimisers. I suspect the majority of minimizers currently used in fitbenchmarking would fail on such a suite.

As part of such benchmarking it's not only the time taken/function evaluations required that is important. Global minimisers typically don't have a 100% success rate on such difficult problems, so the success rate of a minimiser is a vital statistic. Typically this means one should perform e.g. 50 repeats, and note down the success rate. Time taken and function evaluations are important metrics, but pale in comparison to being able to successfully find the minimum.

**Comment by arm61** [comment]
I think that the aim of FBM (in its current form) is **not** to compare global optimisation, but rather to assess the most efficiency of local minimisers. The utility of this for particular problems is up for debate, but as I understand global optimisation it out of scope for FBM currently. 

However, perhaps @Anders-Markvardsen will disagree with me.

**Comment by tyronerees** [comment]
Personally I think there should be as many problems as possible to test with, so adding problems with many local minima would be interesting -- thanks for pointing us to the scipy benchmark problems @andyfaff. 

This does raise a more general question that we need to address at some point -- as @arm61 says, FitBenchmarking is currently only testing local minimizers, but the 'Accuracy' table is produced with a global metric.  In particular, minimizers that do what they are asked to do by finding a local minimum could be ranked as less good than one that doesn't find a minimum at all, but finds something smaller than a local minimum.

We should have a think about if there's a metric which would actually tell us which method is doing best **on these problems** (e.g., in neutron problems, we're not really interested in minimizing Chi-Squared, but in calculating, say, the atomic mass of a sample).   This would also help compare results obtained between different cost functions, as suggested by @AnthonyLim23.

@nimgould / @Anders-Markvardsen -- I'd be interested to hear your thoughts.

**Comment by andyfaff** [comment]
For programs like sasview I would say that the only thing that counts for an optimiser is its ability to find a global minimum.

**Comment by nimgould** [comment]
I share Tyrone's view that it is perhaps unfair to assess
an algorithm on its ability to find global minima, when
that was never part of its design spec.

As I believe we all know, there are no criteria for checking
global optimality for general functions, smooth or not.
Although global minimization is tractable in low dimensions
in the sense that one can guarantee an iteration sequence {x_k}
will achieve
   f(x_k) - f(x_global) < eps         (*)
for k large enough, there are famous results from the Russian literature 
that say that there exist smooth functions for which the k in (*) will
be at least of the order of (1/eps)^n for minimization in n dimensions
for *any* oracle-based algorithm; think of an oracle as something that
given an x, returns information about the minimization function at x.
It doesn't take eps to be too small (say 0.01) or n too large
(say 20) before this bound will exceed your or my computational
lifetimes.

Of course, not all functions ... indeed presumably not many ... will
behave like this, but my point about not being able to identify
global optima remains. If we are fitting 5 parameters, there is
realistic hope, and we should be trying to achieve it. But not with
local minimization methods.

Nick

-- 
Nicholas I. M. Gould
Scientific Computing Department            email: nick.gould@stfc.ac.uk
G39, R71 Rutherford Appleton Laboratory    phone: 0(44)1235 445801
Chilton, Oxon OX11 0QX England EU
www: http://www.numerical.rl.ac.uk/people/nimg

**Comment by Anders-Markvardsen** [comment]
To resonate what @arm61 writes the work of FitBenchmarking is purposely focussed on comparing local minimizers - not because we didn't want to consider global miniminer problems or global minimzer like problems - but simply because 1) most science software in our community cares primarily about local minimization and its stability and speed issues 2) our limited (but growing!) developer contributions is focussed on delivering this first. So extending it to comparing global miniminer is desirable, a natural extension and will be fun to do. Maybe we are getting closer to consider this stage? But as already alluded to in the comments above, to do this in a meaningful and useful way will not be trivial to do. @andyfaff we have weekly Friday catch-ups (13:00 UK time, may not work for your time zone - not sure) where people can dial in, and you would of course also be very welcome to join one of these (or more!) – just say. Otherwise, I suggest keeping this issue open for further comments, discussions etc. and a place to give updates on our incremental journey towards, in some way, testing global minimizers.
