### ISSUE TITLE
Change read_file and close_file in BaseFittingProblem to use context manager

### ISSUE THREAD

**Issue by TOFarmer** [fitbenchmarking/fitbenchmarking#271]
**Description**
`BaseFittingProblem` uses `read_file` and `close_file` methods for file handling.  This should be refactored so that a context manager is used (i.e. `with open(file) as file_handler`).  This eliminates the risk of file handling problems which result from exceptions.  Currently read_file and close_file are called in `parse_sasview_data.FittingProblem.__init__` 10 lines apart - if anything an exception is thrown during any of these 10 lines, the file will not be closed.

**Suggested Fix**
Either `BaseFittingProblem` could be made into a context manager, or it could simply use `open` as a context manager.

**Comment by AndrewLister-STFC** [comment]
Will be done as part of the work on #264
