### ISSUE TITLE
Additional RALFit options

### ISSUE THREAD

**Issue by wathen** [fitbenchmarking/fitbenchmarking#286]
**Is your feature request related to a problem? Please describe.**
There are different options within `RALFit` (see [here](https://ralfit.readthedocs.io/projects/Python/en/latest/method.html)) which can be added to `fitbenchmarking_default_options.json`. 

**Describe the solution you'd like**
Pass additional options from json file to the `RALFit` controller.

**Comment by tyronerees** [comment]
closed by PR #302
