### ISSUE TITLE
Example run scripts should be renamed and should have argparser

### ISSUE THREAD

**Issue by TOFarmer** [fitbenchmarking/fitbenchmarking#287]
**Is your feature request related to a problem? Please describe.**
The example run scripts run from main and take command line arguments.  As these currently use sys.argv, they have to be in a specific order, can be passed as any type, and have no associated documentation - the user has to look at the code in order to determine what command line arguments they can pass, what form they should take and what they do.

**Describe the solution you'd like**
Use `argparser` to manage these command line arguments.  This should include:
- short and long tags for all arguments (e.g. `-f` and `--file`)
- types
- nargs
- help messages

**Comment by AndrewLister-STFC** [comment]
Updated the name as we discussed this last Friday and decided example_run_script is not really an example anymore
