### ISSUE TITLE
Parametrise Controller tests

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#292]
**Which module and class/method/function does this relate to?**
The controllers

**What aspect requires additional tests?**
The tests should be parametrised to reduce burden when adding new controllers (as mentioned in #273)

**Is this a unit, system or functional test?**
Unit

**Additional context**
This would also make adding additional tests easier.

**Comment by tyronerees** [comment]
This is obsolete since we have the shared testing framework
