### ISSUE TITLE
Create a Jacobian and residual evaluation function in the fitting problem

### ISSUE THREAD

**Issue by wathen** [fitbenchmarking/fitbenchmarking#294]
When adding RALFit (#215) you have to supply Jacobians and residuals to the software. Currently the Jacobians is done by using `SciPy` in the RALFit controller. We should create two new functions `eval_j` and `eval_r` which evaluate the Jacobian and residual (`y - eval_f(x)`) in the fitting problem, similar to `eval_f`. 

Blocked by #283

**Comment by AndrewLister-STFC** [comment]
Blocked until #322  and #323 are done
