### ISSUE TITLE
Mantids ties are ignored by software that is not mantid

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#303]
**Description of the error**
Using ties on a mantid function with non-mantid fitting software seems to have no impact. This could explain why GEM is problematic.

**Describe the expected result**
Setting a tie should fix a parameter.

**Describe the actual result**
Running FitBenchmarking with ties and without gives the same result.

**Suggested fix**
We should consider whether this is something that should be supported if we have to jump through hoops to make it work for non-mantid fitting software.

**Additional details**
This currently works for Mantid fitting.

**Comment by Anders-Markvardsen** [comment]
As a minimum for MVP is that we document this to the user
