### ISSUE TITLE
Runtime information for user

### ISSUE THREAD

**Issue by wathen** [fitbenchmarking/fitbenchmarking#331]
When running fitbenchmarking the only output, during runtime, is from Mantid. It would be nice to have some like this:

`Running: Problem set 1`
`        Software: Scipy`
`                Running minimizer: LM`
`                Running minimizer: TRF`

or at least something like this to give up to date information for the user.

**Comment by tyronerees** [comment]
I think this is a duplicate of #255 (in spirit, if not in implementation).  This is easy to put in, whereas the status bar in #255 is tricky until we can handle mantid output better, so I'll close that issue as a duplicate.
