### ISSUE TITLE
Remove fitting/misc.py 

### ISSUE THREAD

**Issue by wathen** [fitbenchmarking/fitbenchmarking#346]
In `fitting/misc.py` there are two function, namely, `compute_chisq` and `create_result_entry`. 

Currently the `compute_chisq` function is is pretty much the same as `FittingProblem.eval_r_norm`, we should remove this and call `FittingProblem.eval_r_norm` when computing the chisq value.

The function `create_result_entry` generates a blank class and populates the attributes
```
result = fitbm_result.FittingResult()

# Populate result object
result.problem = problem
result.fit_status = status
```
This should be changed to 
`result = fitbm_result.FittingResult(problem, status, ...)`
and would then remove this function

**Comment by AndrewLister-STFC** [comment]
Closed by #348
