### ISSUE TITLE
Folder restructure

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#347]
**Is your feature request related to a problem? Please describe.**
Current folder structure is confusing as some python files are in the root directory of the source, and some are in a nested package:
e.g. 
`fitbenchmarking/fitbenchmark_one_prob.py` and `fitbenchmark/fitting/controllers/…`

**Describe the solution you'd like**
We should review this and look at moving to a structure where `parsers`, `controllers`, and `core` are in the top level, with these stand alone files moved into core. This might look like:

```
fitbenchmarking
|\_ fitbenchmarking
|   |\_ core
|   |   |\_ fitbenchmark_one_prob.py
|   |   \__ ...
|   |\_ parsers
|   |   |\_ sasview.py
|   |   |\_ mantid.py
|   |   \__ ...
|   |\_ controllers
|   |   \__ ...
|   \__ systests
|       \__ ...
|\_ examples
|   \__ ...
|\_ setup.py
\__ ...
```

This has the benefit of moving all extensible packages to the top level and indicating what we consider the core code. It would then be obvious where to add tests for these core files (which are currently untested).
I'm also hoping this would help with the fact that we have multiple misc.py files.

**Comment by wathen** [comment]
I've had a look at the misc.py files, fitting/misc.py will be deleted once #346 is completed and it seems the three functions in resproc/misc.py (`display_name_for_minimizers`,`weighted_suffix_string` and `build_items_links`) are only used in the test file (`resproc/tests/test_misc.py`) so can be deleted straight away
