### ISSUE TITLE
`eval_r_norm` defaults

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#364]
**Description of the error**
Defaults for `x`, `y` and `e` are not set in `eval_r_norm` 
https://github.com/fitbenchmarking/fitbenchmarking/blob/fe94b04e8a5b560784bc9005209f962f188c960c/fitbenchmarking/parsing/fitting_problem.py#L143-L161

**Describe the expected result**
If `x`, `y` and `e` are not passed in, then these should pick up values from 
`self`, as `eval_r` does.

**Describe the actual result**
`None` is used

**Suggested fix**
Implement this as in `eval_r`

**Comment by wathen** [comment]
It seems that `eval_r` sets the defaults

https://github.com/fitbenchmarking/fitbenchmarking/blob/fe94b04e8a5b560784bc9005209f962f188c960c/fitbenchmarking/parsing/fitting_problem.py#L113-L141
