### ISSUE TITLE
FitBenchmarking exceptions 

### ISSUE THREAD

**Issue by wathen** [fitbenchmarking/fitbenchmarking#391]
**Is your feature request related to a problem? Please describe.**
Observed by @AndrewLister-STFC  in #379.

Create a specific exceptions for FitBenchmarking, e.g., have an `OptionsError` for when incorrect values are set.

**Describe the solution you'd like**
Create FitBenchmarking exception errors to be wrapped around existing functions

**Comment by AndrewLister-STFC** [comment]
These should be handled at the top level to ensure that the software exits gracefully if we raise the error

**Comment by wathen** [comment]
Noticed in adding `controller.check_attributes` in #361, that we should raise a `ControllerAttributeError` or similar when incorrect controller attributes are set
