### ISSUE TITLE
Index page pops up with wrong view

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#399]
This bug may have been reported elsewhere but could not see it. If this the case please just close this issue.

**Description of the error**
Running on Windows, from branch #398, using Python 2.7.

Use an myoptions.ini file with ``software: scipy`` and run ``fitbenchmarking -o examples/myoptions.ini examples/benchmark_problems/simple_tests examples/benchmark_problems/simple_tests`` (or  ``fitbenchmarking -o examples/myoptions.ini examples/benchmark_problems/simple_tests``)

It run, but pop up the view: 
![Capture](https://user-images.githubusercontent.com/1135476/72745021-aa89f800-3ba6-11ea-91c8-325e59ed21de.PNG)

where if I click on any of the Results buttons nothing happens.

Also note if I go to the ``fitbenchmarking\results\simple_tests`` folder and click on ``simple_tests_index.html`` I get the view:

![Capture](https://user-images.githubusercontent.com/1135476/72745157-03599080-3ba7-11ea-8dae-21883fd303e9.PNG)

where again nothing happens if I click on any of the buttons. 

**Describe the expected result**
The expected results is an index page from where I can access the tables, which in the examples above are generated.

**Comment by AndrewLister-STFC** [comment]
@Anders-Markvardsen Can you post the link too? This works on windows, so I'm assuming it's that it needs `file:///` prepending to the link

**Comment by AndrewLister-STFC** [comment]
I've just set it up on my machine and found that it is just missing the `file:///` from the link, or better yet this link should be relative.

I found that going to `simple_tests_index.html` and clicking the buttons worked on my machine though.

**Comment by AndrewLister-STFC** [comment]
I also noticed the graph links are broken. They should have the `file:///` removed from the link as it's a relative path.

**Comment by Anders-Markvardsen** [comment]
thanks - don't hesitate to assign me PR when you think you have fixed it
