### ISSUE TITLE
Update fit problem format to allow for testing against multiple datasets problems

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#4]
Current FitBenchmarking only setup to fit one dataset against one model. This is umbrella issue to extend this to allow benchmarking of one model against multiple datasets where some fit parameters may be global to all datasets and others allowed to be different for individual datasets.

Currently a neutron_data fit problem is defined by the following name/value pairs:

```
name = 'ENGINX 193749 calibration, spectrum 651, peak 20'
input_file = 'ENGINX193749_calibration_spec651.nxs'
function = 'name=LinearBackground;name=BackToBackExponential,I=3527.31,A=1,B=0.05,X0=26185.9,S=29.4219'
fit_ranges = {'x': [26047.3026604, 26393.719109]}
description = ''
```

Change the following

* change fit_parameters to be called fit_properties, since they are properties of the fit, not parameters of a model
* change input_file to a comma separated list of files. Optionally allow each file to contain multiple datasets, e.g. spectra in a Nexus file. 

As an example, where two files the format could be:

```
input_files = ["fname1.txt", "fname2.txt"]
fit_ranges = [{'x': [1.0, 2.0]}, {'x': [2.3, 2.7]}]
```

The function need to be specifiable to specify if a parameter is global or not global, and in such a way that they can work easily with different minimizers in different software packages.

**Comment by AndrewLister-STFC** [comment]
Updating description to fit current expectations

**Comment by AndrewLister-STFC** [comment]
https://docs.mantidproject.org/nightly/algorithms/Fit-v1.html#multiple-fit
Gives some information, and there is an example further down the page.

**Comment by AndrewLister-STFC** [comment]
This is blocked by #303 as it requires ties

**Comment by AndrewLister-STFC** [comment]
This feature will only be available for the Mantid Problems and the Mantid solver, in which case, it should be relatively straight forward.

I am aware that SAS do this too (and call it Simultanous Fitting [here](https://www.sasview.org/docs/user/sasgui/perspectives/fitting/fitting_help.html) however to my knowledge, there is no API into this aspect of SAS and I'm not sure how to do this in bumps as of yet, as there's no obvious information.

**Comment by AndrewLister-STFC** [comment]
Update, SAS wraps a lot of logic around bumps in this part of the code. There's also a comment in bumps warning that the way SAS does it is only available temporarily to support SAS (here)[https://github.com/bumps/bumps/blob/master/bumps/fitproblem.py#L329].

**Comment by AndrewLister-STFC** [comment]
Removing the block as this will be added for just Mantid problems with Mantid functions
