### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#410]
As discussed in sprint planning meeting the structure of the documentation is as follows:

```
Concept
  |\_ What? 
  |\_ Why?
  \__ How?
Users
  |\_ Installation
  |   |\_ FitBenchmarking
  |   \__ Externals
  |\_ Running
  |\_ Outputs
  |\_ Options
  |\_ Tutorial
  |\_ Problem File Formats
  |   |\_ Native
  |   \__ NIST
  \__ Notes
Extending
  |\_ Parsers
  |\_ Controllers
  |\_ Problems
  \__ Outputs
      |\_ Tables
      \__ HTML template
Contributors
  |\_ Guidelines
  |\_ Structure
  \__ Module Index
```

**Comment by AndrewLister-STFC** [comment]
With working on the cutest parser, I think it would also be useful to have a section on "Problem Formats" under "Users".
@tyronerees @wathen Any thoughts on this?

**Comment by AndrewLister-STFC** [comment]
Closing as docs now have this structure and individual issues have been created for each file to be completed.
