### ISSUE TITLE
Different accuracy results depending on order 

### ISSUE THREAD

**Issue by wathen** [fitbenchmarking/fitbenchmarking#437]
**Description of the error**
Observed in #434 that Mantid minimizers on Mantid data gives different results depending which order you run it with:
Scipy then Mantid
![scipy-mantid](https://user-images.githubusercontent.com/15614849/74162502-ccf8b980-4c18-11ea-84ff-6c7ae32aadb5.png)
Mantid then Scipy
![mantid-scipy](https://user-images.githubusercontent.com/15614849/74162544-daae3f00-4c18-11ea-9721-95ea589a6dc9.png)

**Describe the expected result**
Consistent accuracy results that do not depend on the order which they are ran.

**Describe the actual result**
Accuracy results are different depending which software package is run first

**Comment by AndrewLister-STFC** [comment]
This occurs when passing a FunctionWrapper to Mantid. If we instead pass the function string, this is not an issue.
@AnthonyLim23 @Anders-Markvardsen do you know of any odd Mantid behaviour (or caching) when using FunctionWrappers?
The code is in setup in the mantid controller:
```
    def setup(self):
        """
        Setup problem ready to run with Mantid.

        Adds a custom function to Mantid for calling in fit().
        """
        if isinstance(self.problem.function, FunctionWrapper):
            function_def = self.problem.function
        else:
            ...
        self._mantid_function = function_def
```
and changing it to the following fixes it:
```
def setup(self):
        """
        Setup problem ready to run with Mantid.

        Adds a custom function to Mantid for calling in fit().
        """
        # Use the raw string format if this is from a Mantid problem.
        # This enables advanced features such as contraints.
        try:
            function_def = self.problem._mantid_equation
        except AttributeError:
            ...
        self._mantid_function = function_def
```

problem.funtion is created in ``_create_mantid_function`` in fitbenchmark_parser.py by summing objects created using:
```
mantid.simpleapi.__dict__[name](**params)
```
where name is a valid function name such as "DynamicKuboToyabe".

**Comment by AnthonyLim23** [comment]
so mantid can define fit functions in 2 ways.

1. As a string
2. As a function object, see https://docs.mantidproject.org/nightly/concepts/FitFunctionsInPython.html for more details. 

I think the caching should be ok for these. The best people to speak to are Nick and Alice in the Mantid office.

**Comment by AndrewLister-STFC** [comment]
> so mantid can define fit functions in 2 ways.
> 
> As a string
> As a function object, see https://docs.mantidproject.org/nightly/concepts/FitFunctionsInPython.html for more details.
> 
> I think the caching should be ok for these. The best people to speak to are Nick and Alice in the Mantid office.

Ok, I can ask them, when we use the object, we're getting different answers depending on if it runs before or after other minimizers.

**Comment by AndrewLister-STFC** [comment]
This seems to no longer be an issue on master. @wathen can you check if you're still seeing this?
