### ISSUE TITLE
contributors/guidelines docs page

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#447]
Guidelines page needs reviewing (and possibly updating based on what other open source projects do)

**Comment by tyronerees** [comment]
Links to other projects for inspiration include: 

https://github.com/SasView/sasview/wiki/DevNotes_Processes
http://developer.mantidproject.org/

**Comment by tyronerees** [comment]
These were reviewed and updated as part of #530
