### ISSUE TITLE
Jacobian defaults

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#480]
Decide what the default behaviour should be for a Jacobian.  We could enforce a finite difference Jacobian for all, or use analytic Jacobians where available (or something else...)

**Comment by wathen** [comment]
Since more analytic and numerical Jacobians have not been completely implemented yet, we put this on hold till we do

**Comment by Anders-Markvardsen** [comment]
From Friday catch-up: A key part of this will be documentation. For different options tell users what the effect of these have for different minimizers (i.e. we can't necessarily control the Jacobian for all minimizers).

**Comment by tyronerees** [comment]
We've decided the way forward, and will put this in place in the docs as and when we implement the features.  I'm therefore closing the issue.
