### ISSUE TITLE
Poisson cost function

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#490]
Allow the user to select a Poisson cost function to fit the data

**Comment by tyronerees** [comment]
[This](https://github.com/fitbenchmarking/fitbenchmarking/files/5622152/qt19n512k4_noSplash_befa018665f7dc3066e0a52e02d4ae45.1.pdf) paper describes the Poisson cost function

**Comment by AndrewLister-STFC** [comment]
https://data.princeton.edu/wws509/notes/c4.pdf paper descibing fthe poisson
