### ISSUE TITLE
Add a data assimilation problem

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#494]
Add some data assimilation problems (Culham? Reading?)

**Comment by tyronerees** [comment]
A nice description here:
https://earth.esa.int/documents/973910/1002056/DA3.pdf/0cb2d2f6-3724-4089-9bc7-f97a2b4c4cdd
and this paper from Culham:
https://scientific-publications.ukaea.uk/wp-content/uploads/UKAEA-CCFE-CP1909.PDF

**Comment by AndrewLister-STFC** [comment]
@jfowkes found a more detailed Culham!
https://www.researchgate.net/publication/324956488_Data_assimilation_approach_to_analysing_systems_of_ordinary_differential_equations
