### ISSUE TITLE
FitBenchmarking results page button perhaps not needed?

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#508]
**Description of the documentation**
To reproduce on ubuntu

* run fitbenchmarking with e.g. scipy with NIST/average_difficulty

On result page observe:

![Capture](https://user-images.githubusercontent.com/1135476/78390701-e85ec000-75dc-11ea-86e8-fd7e2a64d8ae.PNG)

In this issue either
1. remove buttons, since can e.g. get to "compare table" by clicking on this text
2. or make button somehow look better

**Comment by AndrewLister-STFC** [comment]
@Anders-Markvardsen I think the buttons should now use the correct table icon. Is this sufficient to close this?

**Comment by Anders-Markvardsen** [comment]
Just checked on ubuntu and now see the better icon

![image](https://user-images.githubusercontent.com/1135476/126515195-2f85efb2-cd24-4322-bc4c-8ed0795a1fb0.png)
