### ISSUE TITLE
Split azure build into something similar to that for travis build

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#540]
**Which module and class/method/function does this relate to?**
All modules, because CI build scripts

Maintenance issue coming out from request #526 PR testing.

Done separate here due to ensure proper job done and timing.

Purpose slit azure script in some sensible way and as far as possible have this match with travis split

**Comment by AndrewLister-STFC** [comment]
Closing as we have moved away from azure.
