### ISSUE TITLE
Windows tests error, but report as pass

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#547]
The Azure tests are currently failing, but reporting a pass.

The controller tests give an error, as they look for the tests in the non-existent `test` directory, instead of `tests`:
https://dev.azure.com/fitbenchmarking/fitbenchmarking/_build/results?buildId=129&view=logs&j=19c563d8-3dcd-57d1-cd5e-9dd946b0a29b&t=10ebb82f-a000-5f8e-b96f-1ffc81828e7d&l=156

The Azure yml file should be changed to look for `fitbenchmarking\controllers\tests\test_default_controllers.py`

More importantly, this error is not coming up as a fail for the Windows build.  We need to understand why.

**Comment by tyronerees** [comment]
@Anders-Markvardsen -- could you have a look at this?

**Comment by Anders-Markvardsen** [comment]
Well spotted. That azure passes in this case I think is reasonable and just give warning, i.e. it cannot with certainty know that this was not some intentional

**Comment by Anders-Markvardsen** [comment]
On closer search found https://github.com/microsoft/azure-pipelines-tasks/issues/12874 where other person same issue. Hence this issue is hopefully now fixed and hence close this PR and without merging
