### ISSUE TITLE
Harmonise text in About on www.fitbenchmarking.com with sphinx documentation

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#582]
Harmonise text in https://fitbenchmarking.com/about/ with https://fitbenchmarking.readthedocs.io/en/latest/ . For example *acknowledge funding* is listed on both these pages, and hence the likely that they will at some point fall out of sync. Also, funding is acknowledged on https://github.com/fitbenchmarking/fitbenchmarking/blob/master/README.md.

**Comment by tyronerees** [comment]
The text in `README.md` is canonical, and this is read into the read the docs (see https://github.com/fitbenchmarking/fitbenchmarking/blob/master/docs/source/index.rst), and also our pypi page (https://pypi.org/project/FitBenchmarking/).  

If we wanted to drop these somewhere, I'd suggest dropping on fitbenchmarking.com.  However, I think we can expect a different audience at each of these venues and I'd tend towards keeping the acknowledgements as they are now.  If there was a solution that pulled in a single block of text from somewhere, that would be ideal, but I think is low in the effort vs impact stakes.

**Comment by Anders-Markvardsen** [comment]
I forgot about the above. In that case probably archive this issue?
