### ISSUE TITLE
Use a better first example 

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#589]
**Description of the documentation**
The suggested example is to use the `simple_tests` problem set.

This includes Mantid data, and so will fail if Mantid isn't installed.  Change the default to be, e.g., a set of NIST problems, so that it can be run independently of third party software.

**Comment by jfowkes** [comment]
Indeed just ran into this issue while following the install docs:
```
Error while running FitBenchmarking. Exiting. See below for more information.
Missing dependencies for fit.
Details: Requirements are missing for mantid parser: No module named 'mantid'
```
This could potentially be confusing for new users.
