### ISSUE TITLE
fix nist is_safe

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#601]
**Description of the error**
The function `is_safe`: https://github.com/fitbenchmarking/fitbenchmarking/blob/7c544865b9bd004994a06e8b82357eb28dad6e69/fitbenchmarking/parsing/nist_data_functions.py#L69
strips out `np.<function>` as being safe.  However, `np.pi` is included in this list, and `np.pi` is a constant, not a function.  This can lead to functions like `np.pi * x` being listed as not safe, as they are stripped to the invalid string `*x`, which starts with an operator.  This was the case in a function found in the review of #598.

We should treat `np.pi` differently to functions like `np.cos`, `np.log`, etc -- maybe replacing `np.pi` by `pi`, which can then be treated as a constant?

**Comment by AndrewLister-STFC** [comment]
I think the easiest solution would be removing `np.pi` from the `np_funcs` list and putting in a check for it (`if func_str == "np.pi": return True` or something similar) just before floating points are checked.
