### ISSUE TITLE
Minimizers not run error on release branch

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#659]
**Description of the error**

On the release branch, if I run 
`fitbenchmarking examples/benchmark_problems/NIST/low_difficulty`
(installed via pip), the output I get includes the text:
![image](https://user-images.githubusercontent.com/13645545/95738171-b6f83880-0c80-11eb-8e5b-24981d2bd6d3.png)
This despite all minimizers passing.

- The typos should be fixed `withing --> within`, and reword `...the following minimizers we were not run due to the selected minimizers:`
- This should not appear for a successful run

This happens both on windows and ubuntu

**Comment by tyronerees** [comment]
Just double checked, and this isn't an issue in Master, only the release branch

**Comment by wathen** [comment]
Closed with the merge of #662
