### ISSUE TITLE
Make results web page buttons display better on Windows

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#674]
**To reproduce**
On Windows install and type and run `fitbenchmarking` and observe e.g. the page

![image](https://user-images.githubusercontent.com/1135476/97712492-6b35f380-1ab6-11eb-88cd-d4043bfbbde1.png)

Make the buttons (and possibly other stuff) on this page look more like that you get when running on Linux.

**Comment by jfowkes** [comment]
I'm seeing a similar issue on Mac see below, also not sure what's going on with the math typesetting:
<img width="1280" alt="Screenshot 2020-11-05 at 9 20 02 am" src="https://user-images.githubusercontent.com/5586192/98222053-43c4a800-1f48-11eb-9bfb-231a7cb1338b.png">
