### ISSUE TITLE
Replicate travis-ci linux (and mac) build on azure pipeline

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#682]
With travis-ci possible reaching end of the line, this labelled with high priority

**Comment by AndrewLister-STFC** [comment]
After a lot of testing... (above commits...) I have found:
 - ~Our container does not have sudo installed~
 - Pipelines creates a new user (vsts_azpcontainer) in the container to run jobs with. It also gives it sudo access if sudo is installed.
 - Theres no way to specify the user to use
 - Our container sets up the environment for root on startup
 - Our container does not set up any profile/bashrc/etc. for root (or any other user)

This means:
 - The new vsts_azpcontainer does not have permissions to edit the venv (created by root) without sudo
 - ~The new vsts_azpcontainer cannot get elevated permissions~
 - The new vsts_azpcontainer does not have the right environment
 - Running sudo from vsts_azpcontainer will not give the right environment (as the env is not in a profile)

Solutions!
 - Duplicate the environment setup in the pipeline
 - Set up a profile (/etc/profile) that will be active for all users that sets up the environment
 - Switch to github actions which does allow specifying users

Still to test:
 - If I log out of a container or shut it down, when it starts again, does the env persist? If not, we may want a profile anyway so why switch.
 - Test this on github actions. This is based on the github docs which provide the schema, but I am yet to test it.
