### ISSUE TITLE
Install sudo on docker images

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#693]
**Is your feature request related to a problem? Please describe.**
Porting tests to Azure is not possible as it assumes sudo is installed on the container.
Base containers don't install sudo, so we should do it when we make our images.

**Describe the solution you'd like**
Add installing sudo as one of the docker steps.

**Describe alternatives you've considered**
Alternatively we could try to add sudo during the tests although all of the methods for this I've seen seem somewhat of a hack.

**Additional context**
There is an open issue for this with azure pipelines [here](https://github.com/microsoft/azure-pipelines-agent/issues/2043) (containes some other work-arounds)

**Comment by tyronerees** [comment]
I've just sent an invite to @AndrewLister-STFC to be an owner of the fitbenchmarking team on dockerhub, which should let you change the docker images
