### ISSUE TITLE
Add more SASView examples

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#700]
There are a number of test examples that ship with SASView that we should be able to read out of the box:
https://github.com/SasView/sasview/tree/main/src/sas/sasview/test

Find out what models are appropriate for these data sets, and link them in with FitBenchmarking.

**Comment by AndrewLister-STFC** [comment]
These data sets are not complete (from our perspective) as they miss the model out. Closing as we now have more SAS examples
