### ISSUE TITLE
Plots for jacobian options

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#708]
When cycling through different jacobian options, the plots produced are not correct.  

I'll update with instructions to reproduce later, but I noticed when working on issue #386 that the final(?) params calculated are used to produce a plot for all minimizers, even if multiple jacobians are used

**Comment by AndrewLister-STFC** [comment]
I think this is accross all types of run (not just Jacobians).

After some investigation, it looks like the minimizer is not set correctly in plots. I'll put in a PR for it when my Poisson cost function run finishes.
