### ISSUE TITLE
Minimizer types

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#711]
**Description of the documentation**
There's currently no way for a user who wanted to run a non-ls problem to know which minimizers are available for use. We should auto generate the docs based on the controller `algorithm_check`.

**Comment by tyronerees** [comment]
We should look at this alongside the documentation for the tags introduced in #782

**Comment by AndrewLister-STFC** [comment]
This has been done
