### ISSUE TITLE
Plot of solution found not showing correct lines

### ISSUE THREAD

**Issue by BenPetersRAL** [fitbenchmarking/fitbenchmarking#752]
**Description of the error**
After running `fitbenchmarking` from the windows powershell and clicking on a specific cell in the performance tables of the HTML output, the *plot of solution found* legend always indicates three items: the problem data, the minimizer that was considered a best fit for the problem and the fit produced by dogbox. Also when clicking on a cell of the best fit minimizer for a given problem, the legend still displays two lines in addition to the problem data.

**Describe the expected result**
*When clicking on a cell that is not the best fit for the given problem*: I expected the legend to indicate that in addition to the problem data and the best fitting minimizer for the problem, there would be a line for the minimizer on whose cell I had just clicked.

*When clicking on a cell that is the best fit for the given problem*: I expected the legend only to indicate the problem data and the best fitting minimizer on whose cell I had just clicked.

**Describe the actual result**
*When clicking on a cell that is not the best fit for the given problem (see first screenshot)*: Instead I see the problem data (expected), the best fitting minimizer for the problem (expected) and always the best fit produced by dogbox (for every cell I click on though it is only expected for cells in the dogbox column).

*When clicking on a cell that is the best fit for the given problem (see second screenshot)*: Instead I see the problem data (expected), the best fitting minimizer (expected) and another line pertaining to a minimizer I didn't select.

**Suggested fix**
Ensure that when clicking on a cell that is no the best fit minimizer for a problem, the legend displays the fit according to the minimizer the cell belongs to in addition to the best fit rather than defaulting to dogbox.

No need to plot two lines if the best fit algorithm is selected, so in these cases reduce legend item count from 3 to 2.

**Additional details**
![image](https://user-images.githubusercontent.com/75368443/114190806-a0871d00-9943-11eb-9a92-46a5d5f0adee.png)
![image](https://user-images.githubusercontent.com/75368443/114190630-6ae23400-9943-11eb-8eb7-545551b03cea.png)

**Comment by tyronerees** [comment]
@tyronerees -- try and reproduce this

**Comment by tyronerees** [comment]
I can confirm that this is a problem in the release branch, but is not present in master.

I'll try and find the commit that fixed this in master and will cherry pick it into the release

**Comment by tyronerees** [comment]
This was fixed in master in #712.

I've just cherry picked and pushed this to the release branch, and it will be fixed in release 0.1.3.
