### ISSUE TITLE
Extra dependencies windows installation error

### ISSUE THREAD

**Issue by BenPetersRAL** [fitbenchmarking/fitbenchmarking#753]
**Description of the error**
Running from a Windows 10 OS, when installing FitBenchmarking via pip from the windows powershell using the first installation command in the installation documentation

    python -m pip install fitbenchmarking[bumps,DFO,minuit,SAS,numdifftools]
 
I encountered several errors and it took some manual intervention to complete the installation. First I encountered an error pertaining to C++ installation:

    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": 
    https://visualstudio.microsoft.com/downloads/ 

After installing Microsoft Visual Studio 2019, this error disappeared and then I encountered a warning about the *numdifftools* installation (`WARNING: fitbenchmarking 0.1.0 does not provide the extra 'numdifftools' ` and an error relating to the *Minuit* fitting package installation:

    Using legacy 'setup.py install' for iminuit, since package 'wheel' is not installed. 
    Installing collected packages: sasmodels, iminuit, fitbenchmarking 
        Running setup.py install for iminuit ... error
             creating build\temp.win-amd64-3.9\Release\Users\cph47349\AppData\Local\Temp\pip-install-mmf66kj8\iminuit_a383db82cc054e3e98adf0b5a1073e5c\extern\root\math\minuit2 
             error: could not create 'build\temp.win-amd64-3.9\Release\Users\cph47349\AppData\Local\Temp\pip-install-mmf66kj8\iminuit_a383db82cc054e3e98adf0b5a1073e5c\extern\root\math\minuit2': The filename or extension is too 
             long

I installed the *wheel* package and retried but then got a similar error:

        Building wheels for collected packages: iminuit 
          Building wheel for iminuit (setup.py) ... error
        error: could not create 'build\temp.win-amd64-3.9\Release\Users\cph47349\AppData\Local\Temp\pip-install-jtz_kn7u\iminuit_d64f72fbc74042bfa456a820116e40e5\extern\root\math\minuit2': The filename or extension is too long 

**Describe the expected result**
I expected FitBenchmarking and the extra-dependencies to install using pip with no intervention.

**Describe the actual result**
Following the running of `python -m pip install fitbenchmarking[bumps,DFO,minuit,SAS,numdifftools]` I had to install visual studio 2019 for C++ (not mentioned as a requirement in documentation) and due to the error shown in the first section I resorted to using the pip installer for the *Minuit* and *numdifftools*:

      python -m pip install iminuit
      python -m pip install numdifftools

I followed this with a re-run of  `python -m pip install fitbenchmarking[bumps,DFO,minuit,SAS,numdifftools]` thinking it may notify me that all required packages were already installed but it tried to uninstall the existing iminuit package then reinstall it which resulted in the same error `The filename or extension is too long` followed by `Rolling back uninstall of iminuit`.

**Suggested fix**
Provide different advice to windows 10 users whilst this installation issue is fixed, maybe suggest the extra dependency packages are installed as separate commands in pip.

**Additional details**
N/A

**Comment by Anders-Markvardsen** [comment]
Observe this reported bug also on Windows. More specifically:

1. wiped all python installs
2. installed 3.9.6
3. ran `python -m pip install fitbenchmarking[bumps,DFO,minuit,SAS]` and observe the error
```
    Running setup.py install for iminuit ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ajm64\\AppData\\Local\\Temp\\pip-install-03a9bmez\\iminuit_6dd81da43c5b4f9b92e5f869a6fcb5f8\\setup.py'"'"'; __file__='"'"'C:\\Users\\ajm64\\AppData\\Local\\Temp\\pip-install-03a9bmez\\iminuit_6dd81da43c5b4f9b92e5f869a6fcb5f8\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ajm64\AppData\Local\Temp\pip-record-11471950\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python39\Include\iminuit'
```

Hence, this confirm default installation does not work and as per https://fitbenchmarking.readthedocs.io/en/stable/users/install_instructions/fitbenchmarking.html

Fixed this by observing how installation is done with Github action and https://github.com/fitbenchmarking/fitbenchmarking/blob/master/.github/workflows/main.yml where the steps are different and 
```
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .[bumps,DFO,gradient_free,minuit,SAS,numdifftools]
```

One question @AndrewLister-STFC , should `pip install -r requirements.txt` be executed after `pip install` in github actions? That is to test that can install software with one line.

**Comment by robertapplin** [comment]
On the cmd line, I created a virtual environment to try replicate this
```
py -m venv user-env
```
Activated the environment
```
.\user-env\Scripts\activate
```
Then tried the first install command in the documentation
```
python -m pip install fitbenchmarking[bumps,DFO,minuit,SAS,numdifftools]
```
And got the same error as above.

**Comment by robertapplin** [comment]
The same error doesn't occur when installing from source (as is done in the github actions). Hence the PR swapping around the requirements install (#922) does not fail.

@Anders-Markvardsen Should a new job be added to the github actions which does the install from a user perspective to make sure it works?

**Comment by Anders-Markvardsen** [comment]
> The same error doesn't occur when installing from source (as is done in the github actions). Hence the PR swapping around the requirements install (#922) does not fail.
> 
> @Anders-Markvardsen Should a new job be added to the github actions which does the install from a user perspective, i.e. not from source, to make sure it works in future?

@robertapplin nice approach and yes, thanks

**Comment by robertapplin** [comment]
The install does not work with Python 3.9.7 as it will not download the wheel (`.whl`) file for the `iminuit` package, and this is when the above error occurs. The install works fine for Python 3.8.10 as it finds and downloads `iminuit-1.5.4-cp38-cp38-win_amd64.whl`

**Comment by robertapplin** [comment]
I believe iminuit doesn't provide support for a binary wheel for Python 3.9.7. In the documentation it mentions that in this case a C++ compiler is required https://github.com/scikit-hep/iminuit/blob/71fe8c2c74c5cdbd9467d06530e88eb5c93ac792/doc/install.rst

**Comment by robertapplin** [comment]
I've found that installing `iminuit>=2.0` instead of `iminuit<2` solves the issue. In setup.py on master, `iminuit>=2.0` is already being installed and hence installing from source still works using
```
python -m pip install .[bumps,DFO,gradient_free,minuit,SAS,numdifftools]
```
Installing the release version doesn't work however as it uses `iminuit<2`, and there must have been a package change since the last release.

To detect package changes that break the installation workflow, a nightly build would be useful which tests the installation of the release and of the master code
