### ISSUE TITLE
FitBenchmarking --help example not working

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#773]
**Description of the error**

Running `fitbenchmarking --help` tells users:

```
usage: FitBenchmarking [-h] [-o OPTIONS_FILE]
                       [-p PROBLEM_SETS [PROBLEM_SETS ...]] [-d]

optional arguments:
  -h, --help            show this help message and exit
  -o OPTIONS_FILE, --options-file OPTIONS_FILE
                        The path to a FitBenchmarking options file
  -p PROBLEM_SETS [PROBLEM_SETS ...], --problem_sets PROBLEM_SETS [PROBLEM_SETS ...]
                        Paths to directories containing problem sets.
  -d, --debug-mode      Enable debug mode (prints traceback)

Usage Examples:

    $ fitbenchmarking
    $ fitbenchmarking -p examples/benchmark_problems/NIST/*
    $ fitbenchmarking -o examples/options_template.ini     -p examples/benchmark_problems/simple_tests     examples/benchmark_problems/Muon
```

However when running `fitbenchmarking -o examples/options_template.ini     -p examples/benchmark_problems/simple_tests` then get error:

```
Error while running FitBenchmarking. Exiting. See below for more information.
Failed to process options.
Details: The option 'external_output: no' in the ini file is invalid. external_output must be on or more of ['debug', 'display', 'log_only']
```

**To fix**
Two things:

* change `external_output` to be the default and with explanation of other values or reference to where get info of what `external_output` is
* add CI test for the examples we currently provide to users. Suggest a test where strip out the examples from `fitbenchmarking --help` and run these; preferably checking the output returned, but as a minimum that the examples run without bailing out

**Comment by AndrewLister-STFC** [comment]
We should add unit tests for these.
