### ISSUE TITLE
Failed minimizers report in results GUI typos & bugs

### ISSUE THREAD

**Issue by BenPetersRAL** [fitbenchmarking/fitbenchmarking#800]
**Description of the documentation**
In the results GUI there are a few noticeable typos/errors that should be corrected when the "Failed minimizers" report is included. See the screenshot below that was taken when running all of the the default softwares when "algorithm_type" was set to "general". The red annotation highlights the typos, the green highlights the unnecessary repetition of the minimizers that did not run and the blue highlights the occasions where the software is announced despite none of it's minimizers failing.

![image](https://user-images.githubusercontent.com/75368443/118504513-7c2d1600-b723-11eb-8831-e886f7b87017.png)

**Comment by jess-farmer** [comment]
Fixed by #818
