### ISSUE TITLE
Error with mantid problems and matlab fitting

### ISSUE THREAD

**Issue by jess-farmer** [fitbenchmarking/fitbenchmarking#802]
**Description of the error**
When running Mantid problems with Matlab fitting software, the serialization of `self.cost_func.eval_model` in the Matlab Controller causes the following error:
`Pickling of "_api.CompositeFunction" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)`
As a result, all Mantid problems are skipped over.

**Describe the expected result**
Mantid problems should be able to be run with matlab fitting software selected in options.

**Describe the actual result**
No results produced for Mantid problems when run with matlab fitting software

**Suggested fix**
There should either be a workaround for having to pickle `self.cost_func.eval_model` to get it to work with matlab, or the function could be somehow modified to make it picklable.

**Comment by AndrewLister-STFC** [comment]
The latest error I get is:
```
Python Error: ImportError: First import of "._kernel" failed with "No module named 'mantid.kernel._kernel'". Second import of "_kernel" failed with "/home/eel23943/MATLAB/R2021a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/eel23943/mantid-build/bin/_kernel.so)"
```
It seems that mantid can't be imported into matlab so I'm going to just put a verification check in for this combo...
