### ISSUE TITLE
Axes of results plots not fit for SASView problems

### ISSUE THREAD

**Issue by BenPetersRAL** [fitbenchmarking/fitbenchmarking#815]
SASView problems consist of data of Intensity vs Q (units of distance Angstroms (10^-10m)). The current axes of the plots in the fitbenchmarking results viewer has "Time (\mu s)" on the x axis which is just not applicable in the case of SAS problems of the type that the SASView example problem sets will consist of.

Secondly, when wanting to check the goodness of fit by eye, it is very difficult to interpret on a linear scale. A log vs log plot would be ideal for this data.

**Proposed Solution**
The renaming of the x axis to something like "arbitrary units" so that it can be applied to all problems.

The option to introduce a log scale on both the x and y axis for viewing the sas problem data.

**Additional context**
See below how data appear in the results browser:
![image](https://user-images.githubusercontent.com/75368443/120014535-19b4ff00-bfda-11eb-98b9-bed0dc1a644d.png)

See how data would ideally appear on a log-log plot:
![image](https://user-images.githubusercontent.com/75368443/120014632-33eedd00-bfda-11eb-8afc-f9688b0072fc.png)

**Comment by AndrewLister-STFC** [comment]
FIxed by #833
