### ISSUE TITLE
Document what to do when new data is added

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#861]
We should describe how to add a new data set -- we have documentation for new parsers, but not for new data sets using existing parsers.  Things to describe (and decide!):
- where does the data set get documented?
- how and where do you add the tar.gz/zip files?
- are these updated every release?

**Comment by AndrewLister-STFC** [comment]
Assets cons:
-  Possibly not big enough?
-  Want to decouple data from FitBenchmarking at some point
