### ISSUE TITLE
Allow users to hide/show columns in the html tables

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#872]
**Is your feature request related to a problem? Please describe.**
I found this http://jsfiddle.net/d6JWV/575/ which has an example of how we can toggle the visibility of a column. It would be nice if we use something like this to toggle columns in our results tables. E.g. all of the results for a certain software.

**Comment by robertapplin** [comment]
Another good example https://www.w3schools.com/jquerymobile/tryit.asp?filename=tryjqmob_tables_columntoggle
