### ISSUE TITLE
Review plotting tools

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#907]
There are a number of plotting tools which offer various advantages to our current approach with varying costs.
I think it would be good to look into the options and experiment to see if we can improve the plotting time/interactivity.

Perhaps we should even consider having 2 plotting engines - one with a focus on time and one focusing on interactivity/aesthetics.

Some packages to consider:
- matplotlib: It's what we currently use, is the standard python package for plotting, let's us do fancy things like updating just 1 line to save plotting time, and is a good baseline.
- plotly: This seems to offer much cleaner looking graphs with interactive html pages which could be very nice for the results pages. In a comparison online this was much slower than matplotlib but we should test how much.
- altair: This looks similar to plotly but with a different back end. Again it would be good to do simple timing tests.
- pyqtgraph: This is based on Qt. It quotes matplotlibs biggest weakness as it's speed (wrt. rapid plot updates) so may be faster.
- [This StackOverflow post](https://stackoverflow.com/questions/7503164/how-do-i-increase-the-speed-of-plotting-in-python) suggests GNUPlot via a python interface for speed.
- ???: If any others are known add them to the list!

**Comment by AndrewLister-STFC** [comment]
We should start by coming up with a list of requirements before doing a lot of research into what's available so that we can focus on prioritising features

**Comment by AndrewLister-STFC** [comment]
Feature requests:
1) The results plotting should be significantly faster than the fitting.
2) Should look visually appealing -- no decrease in quality
3) Decoupled from fitting so can replot
3a) Combine multiple datasets
4) Save as vector graphic (pdf?)
5) Choose colours
6) Performance profiles: Remove lines (and recompute)

**Comment by robertapplin** [comment]
| Package       | Aesthetics | Speed  | Interactive |
|--------------|-------------|---------|-------------|
| matplotlib   | right          | $1600  |                   |
| plotly           | centered   |   $12    |                   |
| altair            | are neat    |    $1     |                   |
| pyqtgraph   | are neat    |    $1     |                   |
| GNUPlot      | are neat    |    $1     |                   |

**Comment by tyronerees** [comment]
@robertapplin -- this is great: many thanks! Can you look at https://bokeh.org/ too, and evaluate that -- it also get a few mentions in this space (particularly for working with pandas dataframes)

**Comment by robertapplin** [comment]
The first couple of paragraphs in this link are quite useful to read https://pauliacomi.com/2020/06/07/plotly-v-bokeh.html :

**Plotly:**
```
Plotly is a more platform agnostic framework, attempting to not only bring full-featured bindings for Python, but also for R (and pure JavaScript as well). The folks at Plotly have recently made multiple changes after a new round of seed funding, in particular moving away from the previous business model of attempting to host all graphs on their servers, and placing an emphasis on flexibility. They are attempting to customise their offering to multiple use cases, by using modules that offer access to different functionality through the same underlying framework: besides Plotly, there is Dash for dashboards, Plotly Express for fast figure generation, Figure Factories for complex, preset, layouts, Dash DataTable for tabular display etc. While this means that the library is more fully featured on its own, it can be confusing, as there are multiple ways of getting similar results, with no intuitive explanation as to which should be used. The transition to an investor-backed company also means that Plotly is expected to become profitable somewhere down the line, which raises some question regarding the long-term commitment to open source.
```

**Bokeh:**
```
Bokeh appears to have a much smaller core team, which means that their product is leaner and meaner, with a fairly narrow focus of what the module can and cannot do. On the other hand, the lack of manpower means that they are often slow to bring new features to the code (I am still waiting for a good table component for data) and some bugs can linger for longer that expected. It is Python-centric and deeply integrated with the language, although secondary R, Julia and Scala bindings exist with various states of feature parity. There are also a host of other third party modules, part of the HoloViz framework (like HoloViews, GeoViews and Datashader), which attempt to extend Bokeh (and Matplotlib!) with a higher level interface. Unfortunately, there is a large degree of overlap between features, making their use somewhat confusing.
```
