### ISSUE TITLE
Table key should use relative path

### ISSUE THREAD

**Issue by jfowkes** [fitbenchmarking/fitbenchmarking#911]
The table key should use a relative (not absolute) path otherwise it will not show up in certain cases, e.g. see below:

<img width="1278" alt="Screenshot 2021-08-23 at 9 53 55 am" src="https://user-images.githubusercontent.com/5586192/130419494-d974b470-ad9f-4931-9101-50b3bf7cf5a1.png">

(Here I am serving the results pages to another machine via a ssh tunnel).

**Comment by AndrewLister-STFC** [comment]
We should also mention in the docs that links should be relative

**Comment by robertapplin** [comment]
I am seeing in the latest fitbenchmarking that the colourbar directory is None
![image](https://user-images.githubusercontent.com/40830825/133102203-0a8639a1-bc70-4edc-9c62-307602771529.png)

I think this 'None' bug was potentially introduced in https://github.com/fitbenchmarking/fitbenchmarking/commit/eb2b237f73c8d411eb6874bfb9e899e8f87bf2ec
