### ISSUE TITLE
Mantid minimizers don't work with `weighted_nlls` cost function

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#938]
The following ini file:
```
[MINIMIZERS]
scipy_ls: lm-scipy
mantid: Levenberg-Marquardt
        Levenberg-MarquardtMD
bumps: lm-bumps
gsl: lmder
     lmsder

[JACOBIAN]
scipy: 2-point

[FITTING]
num_runs: 1
software: scipy_ls
	  mantid
	  bumps
	  gsl
jac_method: scipy
cost_func_type: weighted_nlls
# cost_func_type: nlls
```
run on the simple_tests problems gives the following output:
![image](https://user-images.githubusercontent.com/13645545/136400007-620b6e94-cdc2-4fef-8cbf-e33aa9ae28b9.png)
The problems of the form `xxx-fb[a|b]` are mantid problems, and mantid deals with them as expected.  The problems of the form `xxx, Start [1|2]` are NIST problems, and mantid fails to converge.

Changing the cost function to `nlls` gives expected behaviour.  ~~I suspect this is due to the cost function being inferred by the Jacobian (so the weighted cost function will divide by the weights), whereas Mantid uses it's own internal logic to set the different cost function from the 'basic' cost function.~~ On closer inspection, we never send the Jacobian in, so that's a red herring.  Does the function evaluation we send in change based on the cost function?

**Comment by robertapplin** [comment]
The current theory is that the Jacobian is being weighted twice (once by the Mantid software and once by fit benchmarking). If I attempt to un-weight one of these weightings then I get the following results:
![image](https://user-images.githubusercontent.com/40830825/137882678-32d3d834-c037-4228-8672-63558f2017ca.png)

@tyronerees says these results look good. At the moment, the Scipy Jacobian in fit benchmarking holds a cost function which does some weighting operation, but this dependency on the fit benchmarking cost function is not ideal when we have a software like mantid which implements its own cost functions. A separate issue to fix this will be opened, and hopefully fixing that should fix this issue.
