### ISSUE TITLE
Extend the regression tests

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#939]
The regression tests should be extended so that they test all deterministic fitting packages supported by fitbenchmarking. The packages currently missing from the `all` test type are:
- [ ] `dfo`
- [ ] `gradient_free` (requires bounds)
- [ ] #968
- [ ] `scipy_go` (requires bounds)
- [ ] The `matlab` regression tests aren't currently being run because of licensing issues

**Comment by robertapplin** [comment]
Is this a duplicated of #946 ?

**Comment by robertapplin** [comment]
Changed the description of this issue because I think the old description was the same as #946. But extending the regression tests to include some of the newer fitting packages I think is a good idea, especially as the `all` test type suggests it should test everything.

**Comment by robertapplin** [comment]
`gradient_free` and `scipy_go` will be left out of the regression tests for now because they require bounds
