### ISSUE TITLE
Change regression tests to test against *working* minimizers

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#946]
**Description of the error**
Current regression tests test against the first minimizer (alphabetically). While this is easier to extend, it is not robust at spotting breaking changes!

**Describe the expected result**
Any change in the regression tests is easy to see if it is trivial or breaking.

**Describe the actual result**
The tests can change by seemingly insignificant values when the change breaks better minimizers.

**Comment by robertapplin** [comment]
@tyronerees @AndrewLister-STFC What minimizers do we want to test against for `bumps`, `gsl`, `ralfit`, `scipy` and `scipy_ls`?

I'm guessing `lm-bumps` for `bumps`, but I'm not sure about the others

**Comment by robertapplin** [comment]
And same question for `matlab_curve` and `matlab_opt`?

**Comment by tyronerees** [comment]
I'd say test again Levenberg-Marquardt, where available, as we'll at least get a reasonable answer.  So, try:

| Software | Minimizer|
|:----------|:------------|
| `bumps` |  `lm-bumps`    |
|`gsl`        |   `lmsder`         |
|`ralfit`     |   `hybrid`           |
|`scipy`    |   `TNC`(?)              |
|`scipy_ls`|   `lm-scipy`     |
|`matlab_curve` |   `Levenberg-Marquardt`      |
| `matlab_opt` |  ` levenberg-marquardt`        |

**Comment by robertapplin** [comment]
`TNC` seems to give a worse result for scipy than `Nelder-Mead` so I have switched it back to `Nelder-Mead` for now
