### ISSUE TITLE
Jacobian files should return the jacobian of the function not  the residual (negated function)

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#956]
**Description of the error**
Current problem jacobians return the negative of the jacobian.

**Describe the expected result**
This jacobian should be correct

**Describe the actual result**
It's negated

**Suggested fix**
Update the jacobian files for problems and negate the logic in the analytic jacobian class. (And check the cutest ones...)

**Comment by jfowkes** [comment]
Has this not been fixed by #951?

**Comment by AndrewLister-STFC** [comment]
> 
> 
> Has this not been fixed by #951?

No, the data files for NIST examples are written with `y-f(x,p)` in mind rather than just the jacobian of the function. Currently the parser fixes that on read (I think).
