### ISSUE TITLE
Error in hessian options docs

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#974]
The docs say that `hes_method` can be one of four options:
![image](https://user-images.githubusercontent.com/13645545/142031934-fa0b425b-b424-49fb-9d92-d14450c69e04.png)
but the code says only `default` and `analytic` are supported:
![image](https://user-images.githubusercontent.com/13645545/142032046-b813cc7a-4cf1-4e79-a045-5a7cf3fd1d7a.png)

**Comment by AndrewLister-STFC** [comment]
Did you verify this on the latest master?
It seems to work for me running `fitbenchmarking -p examples/benchmark_problems/NIST/average_difficulty/ -o examples/test.ini -d`

With options:
```
[MINIMIZERS]
mantid: Levenberg-Marquardt
        Levenberg-MarquardtMD
scipy: Nelder-Mead
       Powell
           CG
           BFGS
           Newton-CG
           L-BFGS-B
           TNC
           SLSQP

[FITTING]
num_runs: 1
software: ralfit
          scipy
cost_func_type: weighted_nlls
algorithm_type: all
jac_method: analytic
            scipy
hes_method: numdifftools
            scipy

[PLOTTING]
make_plots: yes
table_type: acc
            runtime
            compare
            local_min
colour_map: BuPu
cmap_range: [0.4, 0.6]

[LOGGING]
external_output: debug
```

![image](https://user-images.githubusercontent.com/48282025/142448134-f1ed2ba4-237c-48f1-a2c8-d7b28a907693.png)
