### ISSUE TITLE
Performance profiles for large numbers of solvers

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#976]
The performance profiles are unreadable for a large number of solvers:
![image](https://user-images.githubusercontent.com/13645545/142213007-07da2966-1ec7-48c2-a01b-3881c10903dc.png)

- I'm not convinced all the lines are unique
- the legend only shows the first 18 minimizers (there are 149 minimizer options in this test)
- It's clear that there are a handful of good minimizers in the prized top left corner, but I have no idea what they are.

The tables are equally poor for analysis when you have a large number of columns

**Comment by AndrewLister-STFC** [comment]
I think we have 9 colours and 4 line styles so 36 possible unique lines

**Comment by tyronerees** [comment]
OK -- it sounds like there are two actions:
- don't produce a performance profile if testing produces more than 36 columns (and print a warning)
- ensure that the legend includes a label for all of the lines

We also really need to find a way to identify the best performer over all options, because that's not at all clear at the moment.

**Comment by tyronerees** [comment]
closed by #1217
